repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [src]

  - repo: local
    hooks:
      - id: check-commit-msg
        name: check commit message
        entry: python scripts/check_commit_msg.py
        language: system
        stages: [commit-msg]
