from pathlib import Path

REQUIRED = [
    "README.md",
    "LICENSE",
    "CONTRIBUTING.md",
    "CHANGELOG.md",
    "SECURITY.md",
    "pyproject.toml",
    "Makefile",
    ".pre-commit-config.yaml",
    ".gitattributes",
    ".gitmessage",
    ".editorconfig",
    ".yamllint.yml",
    ".markdownlint.yml",
    ".github/workflows/harness-ci.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/CODEOWNERS",
    ".github/dependabot.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    "docs/quickstart.md",
    "docs/fill-guide.md",
    "docs/faq.md",
    "docs/architecture.md",
    "docs/naming-conventions.md",
    "docs/versioning.md",
    "harness/rules/project-structure.md",
    "harness/rules/dev-process.md",
    "harness/rules/coding-standard.md",
    "harness/rules/python-coding-standard.md",
    "harness/rules/python-layers.md",
    "harness/rules/security-standard.md",
    "harness/rules/error-handling.md",
    "harness/rules/logging-standard.md",
    "harness/rules/observability-standard.md",
    "harness/rules/_template.md",
    "harness/agent/application-owner.md",
    "harness/agent/application-owner-python.md",
    "harness/pipeline/stages.md",
    "harness/pipeline/human-checkpoints.md",
    "harness/pipeline/escalation.md",
    "harness/pipeline/hotfix-process.md",
    "harness/pipeline/release-process.md",
    "harness/pipeline/rollback-process.md",
    "harness/metrics/metrics.md",
    "harness/metrics/dashboard.md",
    "harness/metrics/collection.md",
    "harness/iteration/patch-log.md",
    "harness/iteration/README.md",
    "harness/sources/README.md",
    "harness/agents/README.md",
    "harness/agents/orchestrator.md",
    "harness/agents/architecture-agent.md",
    "harness/agents/incident-agent.md",
    "harness/agents/review-agent.md",
    "harness/agents/code-archaeology-agent.md",
    "harness/agents/data-modeling-agent.md",
    "harness/agents/gate-agent.md",
    "harness/changes/README.md",
    "harness/changes/_template/README.md",
    "harness/changes/_template/requirement-analysis.md",
    "harness/changes/_template/task-breakdown.md",
    "harness/changes/_template/coding-report.md",
    "harness/changes/_template/review-record-v1.md",
    "harness/changes/_template/unit-test-report.md",
    "harness/changes/_template/ci-result.md",
    "harness/changes/_template/deploy-validation.md",
    "scripts/check_pytest_report.py",
    "scripts/check_python_rules.py",
    "scripts/check_harness_docs.py",
    "scripts/check_layers.py",
    "scripts/check_commit_msg.py",
    "scripts/check_secrets.py",
    "scripts/check_gates.sh",
    "scripts/install-hooks.sh",
    "scripts/dev-setup.sh",
    "scripts/validate_schemas.py",
    "tests/README.md",
    "tests/conftest.py",
    "tests/test_smoke.py",
    "tests/test_scripts.py",
]


def main() -> None:
    missing = [p for p in REQUIRED if not Path(p).exists()]
    if missing:
        raise SystemExit("Missing harness docs:\n" + "\n".join(missing))
    print(f"Harness docs check passed ({len(REQUIRED)} files)")


if __name__ == "__main__":
    main()